# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763351e9067352cf246cd920fca97713711e3c809182ffa8f1843e603cace9545c68f524cd178ec13d0fb611f6ae851f09700579cad5796ccf1ca2e865b3d00f
  gmail_email: 'foodgenieapp@gmail.com'
  gmail_password: 'Bl45sFnsS1mYBxKwFkiEGw'
  google_client_id: '977779467867-52tmt08vfia27qn2k1kb4b3tcam5tum5.apps.googleusercontent.com'
  google_client_secret: 'uOphw1WgmoMQUvx0l4zx9JYX'
  google_maps_key: 'AIzaSyDZ-VkY2dqYoQpqXhjAus60Ptrg3RqSWiU'
  recaptcha_key: '6LdzqP4SAAAAAOt7ZexyfE-YluoHaATrO4K95u8g'
  recaptcha_secret: '6LdzqP4SAAAAAPin34EtH3tEodYK1OWelVgePGiD'
  validic_org: '53f3945bedd24214d70000ba'
  validic_token: 'bbe4cb71d462301de6be3a01530772f37fbbdbbe193dd1c2f5d18e02beb89f64'
  w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_app: Vmsh_-BQYtqz4uKx
  w3gram_secret: FD6pz7A3cPoNF7ZqYUYFc2bISFCLJzWzuMPG8xJr5XQ

test:
  secret_key_base: 40ceb33b612132825fbd97f37530db6a0898e32cb8ea5d8cbb3322e44e3a95629b730a8fe5db59d96e5116100e7586d8cadac858c14fc85cc7c628e7d0148788
  gmail_email: 'foodgenieapp@gmail.com'
  gmail_password: 'Bl45sFnsS1mYBxKwFkiEGw'
  google_client_id: '977779467867-52tmt08vfia27qn2k1kb4b3tcam5tum5.apps.googleusercontent.com'
  google_client_secret: 'uOphw1WgmoMQUvx0l4zx9JYX'
  google_maps_key: 'AIzaSyDZ-VkY2dqYoQpqXhjAus60Ptrg3RqSWiU'
  recaptcha_key: '6LdzqP4SAAAAAOt7ZexyfE-YluoHaATrO4K95u8g'
  recaptcha_secret: '6LdzqP4SAAAAAPin34EtH3tEodYK1OWelVgePGiD'
  validic_org: '53f3945bedd24214d70000ba'
  validic_token: 'bbe4cb71d462301de6be3a01530772f37fbbdbbe193dd1c2f5d18e02beb89f64'
  w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_app: Vmsh_-BQYtqz4uKx
  w3gram_secret: FD6pz7A3cPoNF7ZqYUYFc2bISFCLJzWzuMPG8xJr5XQ

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].inspect %>
  gmail_email: 'foodgenieapp@gmail.com'
  gmail_password: <%= ENV["GMAIL_PASSWORD"].inspect %>
  google_client_id: '977779467867-52tmt08vfia27qn2k1kb4b3tcam5tum5.apps.googleusercontent.com'
  google_client_secret: 'uOphw1WgmoMQUvx0l4zx9JYX'
  google_maps_key: 'AIzaSyDZ-VkY2dqYoQpqXhjAus60Ptrg3RqSWiU'
  recaptcha_key: '6LdqqP4SAAAAACKc3azt_GGJPXJ76f9dDmVIVlvS'
  recaptcha_secret: <%= ENV["RECAPTCHA_SECRET"].inspect %>
  validic_org: <%= ENV["VALIDIC_ORG"].inspect %>
  validic_token: <%= ENV["VALIDIC_TOKEN"].inspect %>
  w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_app: 2bJ9ZfMA5TpIoLXv
  w3gram_secret: <%= ENV["W3GRAM_SECRET"].inspect %>
